
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 06 17:09:43 VET 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 57;
  public static final int MASMAS = 49;
  public static final int DIVIDE = 5;
  public static final int MENOSMENOS = 50;
  public static final int CHAR = 14;
  public static final int UMINUS = 8;
  public static final int ENTERO = 12;
  public static final int CASE = 56;
  public static final int O = 35;
  public static final int DIFERENTE = 31;
  public static final int LPAREN = 20;
  public static final int I = 37;
  public static final int LCORCHETE = 59;
  public static final int FOR = 48;
  public static final int REF = 41;
  public static final int MINUS = 3;
  public static final int RPAREN = 21;
  public static final int MENORIGUAL = 33;
  public static final int ELSEIF = 44;
  public static final int IGUAL = 18;
  public static final int LLLAVE = 26;
  public static final int MASIGUAL = 51;
  public static final int IN = 54;
  public static final int BOOL = 16;
  public static final int OO = 34;
  public static final int DIV = 7;
  public static final int II = 36;
  public static final int RLLAVE = 27;
  public static final int TYPEDEF = 63;
  public static final int PLUS = 2;
  public static final int IF = 43;
  public static final int MAIN = 42;
  public static final int ID = 11;
  public static final int MAYORIGUAL = 32;
  public static final int EOF = 0;
  public static final int RETURN = 58;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int NEGACION = 38;
  public static final int MENOR = 29;
  public static final int MOD = 6;
  public static final int BREAK = 47;
  public static final int VOID = 40;
  public static final int TKSTRING = 23;
  public static final int SWITCH = 55;
  public static final int MAYOR = 28;
  public static final int TIMES = 4;
  public static final int FOREACH = 53;
  public static final int UNION = 62;
  public static final int TKFLOAT = 10;
  public static final int ELSE = 45;
  public static final int PUNTO = 64;
  public static final int READ = 66;
  public static final int IGUALIGUAL = 30;
  public static final int WHILE = 46;
  public static final int RCORCHETE = 60;
  public static final int FLOAT = 13;
  public static final int MENOSIGUAL = 52;
  public static final int STRING = 15;
  public static final int FALSE = 25;
  public static final int STRUCT = 61;
  public static final int TKCHAR = 22;
  public static final int TKENTERO = 9;
  public static final int SUB = 39;
  public static final int PRINT = 65;
  public static final int PYC = 17;
}

